# Generated by Django 4.2 on 2024-02-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_appuser_isstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='isStudent',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
