# Generated by Django 4.2 on 2024-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_feedback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(choices=[('1', 'Highly Not Recommended'), ('2', 'Not Recommended'), ('3', 'Neutral'), ('4', 'Recommended'), ('5', 'Highly Recommended')], max_length=1),
        ),
    ]
