# Generated by Django 4.2 on 2024-03-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_blockedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_teachers', to='webapp.appuser'),
        ),
        migrations.AlterField(
            model_name='blockedstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_students', to='webapp.appuser'),
        ),
    ]
