# Generated by Django 4.2 on 2024-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_appuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
