# Generated by Django 4.2 on 2024-03-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_appuser_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='thumbnail',
            new_name='icon',
        ),
    ]
