# Generated by Django 4.2 on 2024-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_appuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateField(),
        ),
    ]
